name: CI

on:
  push:
    branches:
      - main
  pull_request:
  release:
    types: [published]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Run pytest
        env:
          SYNAPSE_PAT: dummy-token
          TMPDIR: ${{ runner.temp }}
        run: pytest

  # containerize the package and upload to the GHCR upon new release (whether pre-release or not)
  ghcr-build-and-push-on-release:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Extract Release Version
        run: echo "RELEASE_VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
        shell: bash
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image (official release)
        id: docker_build
        if: github.event.release.prerelease == false
        uses: docker/build-push-action@v3
        with:
          push: true
          provenance: false
          tags: ghcr.io/sage-bionetworks/synapse-mcp:latest,ghcr.io/sage-bionetworks/synapse-mcp:${{ env.RELEASE_VERSION }}
          file: ./Dockerfile
          platforms: linux/amd64
          cache-from: type=registry,ref=ghcr.io/sage-bionetworks/synapse-mcp:build-cache
          cache-to: type=registry,mode=max,ref=ghcr.io/sage-bionetworks/synapse-mcp:build-cache
      - name: Build and push Docker image (pre-release)
        id: docker_build_prerelease
        if: github.event.release.prerelease == true
        uses: docker/build-push-action@v3
        with:
          push: true
          provenance: false
          tags: ghcr.io/sage-bionetworks/synapse-mcp:${{ env.RELEASE_VERSION }}-prerelease
          file: ./Dockerfile
          platforms: linux/amd64
          cache-from: type=registry,ref=ghcr.io/sage-bionetworks/synapse-mcp:build-cache-prerelease
          cache-to: type=registry,mode=max,ref=ghcr.io/sage-bionetworks/synapse-mcp:build-cache-prerelease
      - name: Output image digest (official release)
        if: github.event.release.prerelease == false
        run: echo "The image digest for official release is ${{ steps.docker_build.outputs.digest }}"
      - name: Output image digest (pre-release)
        if: github.event.release.prerelease == true
        run: echo "The image digest for pre-release is ${{ steps.docker_build_prerelease.outputs.digest }}"

  # containerize the package and upload to the GHCR upon commit in main
  ghcr-build-and-push-on-main:
    needs: build-and-test
    runs-on: ubuntu-latest
    # TODO: Change to `github.head_ref == 'main'` after testing
    if: github.head_ref == 'dpe-1500-create-ghcr-image'
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image for main
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          push: true
          provenance: false
          tags: ghcr.io/sage-bionetworks/synapse-mcp:main-${{ github.sha }}
          file: ./Dockerfile
          platforms: linux/amd64
          cache-from: type=registry,ref=ghcr.io/sage-bionetworks/synapse-mcp:build-cache
          cache-to: type=inline
      - name: Output image digest
        run: echo "The image digest is ${{ steps.docker_build.outputs.digest }}"
